[phases.setup]
nixPkgs = ["nodejs", "npm", "python3", "pip"]

[phases.install]
cmds = [
  "npm install",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
