services:
  - type: web
    name: trading-analyzer
    env: node
    buildCommand: npm install && npm run build && pip install -r requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
